### ISSUE TITLE
how to add animation when go to next month?

### ISSUE THREAD

**Issue by looping84** [kylestetz/CLNDR#146]
I can't find api  about animation.

**Comment by kylestetz** [comment]
Hey @looping84, unfortunately one of the downsides to using template rendering is that it's difficult to incorporate animation. This is because the entire DOM tree for the calendar is replaced each time it is rendered.

That said, it is possible to do if you create your own controls and use clndr's API to call `next`, `previous` etc. after you've completed your own animations (e.g. fading to white before re-rendering).

Closing this for now, but I am happy to answer specific questions if you have them!
