### ISSUE TITLE
Previous and Next arrows on calendar and parent element

### ISSUE THREAD

**Issue by daviestar** [kylestetz/CLNDR#156]
When trying to quickly hack a datepicker together, I noticed an issue with the previous and next arrows on the calendar.

I'm creating a function where clicking anywhere on the document will close the datepicker, except on the calendar itself.

Consider the following code (where a clndr is wrapped in a div `#event-calendar`):

```
$(document).on('click', datePickerClose);

function datePickerClose(e) {
    if(!$(e.target).parents('#event-calendar').length) {
        $('#event-calendar').css('display', 'none');
    }
}
```

This works fine for all cases except the previous and next arrows.  It seems `e.target` does not recognise these as within the div `#event-calendar`.

The way I got it to work is:

```
function datePickerClose(e) {

    var $this = $(e.target),
        isCal = $this.parents('#event-calendar').length,
        isPrev = $this.hasClass('clndr-previous-button'),
        isNext = $this.hasClass('clndr-next-button');

    if(!isCal && !isPrev && !isNext) {

        $('#event-calendar').css('display', 'none');

    }

}
```

Otherwise, so glad I found this plugin, it's the datepicker of my dreams!! Cheers lads.

**Comment by kylestetz** [comment]
Your fix will work just fine... The reason it's getting weird is because the next and previous buttons in a clndr instance cause the DOM to be destroyed and re-rendered. By the time your event has fired, the next and previous buttons have been removed from the DOM and, while you can still inspect them, they have no parents! This is why you are still able to use `$.hasClass` even though `$.parents` doesn't work for you.

This is all related to the fact that DOM events "bubble" from very specific handlers to generic ones like the one you wrote. Clndr's event handlers are more specific, which means they get called first.

**Comment by daviestar** [comment]
Ah, that makes perfect sense.  Thanks for the explanation :)
