### ISSUE TITLE
IE issue

### ISSUE THREAD

**Issue by L0G1C** [kylestetz/CLNDR#159]
Hey guys,

I could really use some help. Almost done implementing my calendar but running into an issue in IE. Here is my post on stack overflow about it: 

http://stackoverflow.com/questions/29133172/clndr-js-somehow-not-passing-full-days-events-data-to-template-only-in-ie

**Comment by kylestetz** [comment]
Hey, I can run a test on IE10 later today, but for now— your date format `YYYY-M-D` is not a valid format (you want to stick with [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601). Your best shot is to use the format `YYYY-MM-DD`, where single digits are padded with zeros. So, rather than `2015-4-1`, it would be `2015-04-01`.

Could be a totally different issue, but it's worth checking out.

**Comment by L0G1C** [comment]
Wow man, Thanks so much for the quick answer. Right as I came back in to work xD

Yeah that did it, fixed the issue on IE for me. I didn't even think about that man. sigh..so glad haha. Thanks for the help!

**Comment by kylestetz** [comment]
:+1:
