### ISSUE TITLE
Get lowest and highest "visible" adjacent month dates

### ISSUE THREAD

**Issue by L0G1C** [kylestetz/CLNDR#162]
So I'm making some calculations on a week by week basis. And there's obviously some weeks where the previous or next month "bleed" into the current month. This week is an example: 
Sun March 29th - Sat April 4th

So the CLNDR does a good job of showing the adjacent months, but I want to pass the "first day" of the visible month to my ajax call to do the calculations I need. So for the month of April 2015, the begin date would need to be "03/29/15" and the end date needs to be "05/09/15". 

Now obviously I could just load the CLNDR with no data, and then Jquery the values for the first "day" showing in the calendar and last day showing out of the generated Html, but I was wondering if CLNDR had a built-in way to do this.

**Comment by mikegioia** [comment]
This is interesting. Just to clarify, do you mean some way to get the first and last rendered day from the `.clndr()` object? Normally I'd just say exactly what you suggest: `$('#cal').first('.day')...` or something, but it's not nice. Since you have full control over the view, you could also set this info into the data- attribute on the calendar from within the view. Otherwise, I don't see a real need here to add this to the main library.
