### ISSUE TITLE
Events all on same day when using start/end

### ISSUE THREAD

**Issue by babbelnedd** [kylestetz/CLNDR#167]
I want to show the amounts of events per day in each *day-column*. I always get the amount of **all** events on the current date column. When I just use `date` instead of `start` and `end` everything works as expected.

I don't want to use multiday events. Example

    start: 2015-04-10 06:30     end:2015-04-10 07:30

Am I doin somethin wrong here? When I debug my `day` object it really contains all the events.

    <% _.each(days, function(day){ %>
    <div class="col s1_7 cldnr-box">
        <div class="cldnr-content <%= day.classes %>">
            <p><%= day.day %></p>
            <% if(day.events.length > 0) { %>
            <div>
                <p><%= day.events.length %> Events</p>
            </div>
            <% }%>
        </div>
    </div>
    <% }); %>

**Comment by mikegioia** [comment]
`day.events` should contain only the events for that particular day, regardless of multi-day. Are you sure all of your events aren't landing on the same day? If the `date` field on the events is malformed they could all get added for the current day.

Otherwise, is there a config object (with events) that you could send me to recreate the issue?
