### ISSUE TITLE
What happens to the intervals branch?

### ISSUE THREAD

**Issue by kylestetz** [kylestetz/CLNDR#178]
Thanks to @mikegioia the intervals branch has been fixed up (it's at `v1.2.0`).

Merging that with the current branch will _not_ be straightforward, since two new features have been added since then, along with a few bug fixes and updates.

I'm all for merging the changes back into the intervals branch on this repo, and Mike if you're up for it I would support you in trying to merge that work into the main branch. Would be a little tricky, but definitely worth it.

**Comment by mikegioia** [comment]
Ok, I'll try merging master in to intervals in my local version.

**Comment by kylestetz** [comment]
Awesome. If it's going well I am happy to give you commit privileges in this repo!

**Comment by mikegioia** [comment]
Hey Kyle, I just sent the pull request off. Everything looks to be good, but it probably should be reviewed at some pt. I'd love commit privileges. I have a feeling since we're incorporating this into our software product, that I'll be making minor updates here and there. I could run them past you here, or just branch off this repo.

**Comment by kylestetz** [comment]
Amazing!! I might not be able to review it today, but I will take a look as soon as I can.

:beers:

**Comment by mikegioia** [comment]
This is now merged into master
