### ISSUE TITLE
IE not rendering template multi-events correctly

### ISSUE THREAD

**Issue by kevin93w** [kylestetz/CLNDR#189]
Hi,

Recently I used CLNDR for a project mine, where I needed to show three small calendar views of the current and upcoming two months. Because I also needed support for multi-events, I modified the code (template and css) to support this. This works great in all browsers, except for IE where the event gets repeated multiple times and I can't get my hand at why IE is doing this. Do you guys have ever seen this before and any idea why this is happening?

For more information, code and image see my post at StackOverflow: http://stackoverflow.com/questions/31158433/clndr-js-not-displaying-correct-in-ie

**Comment by mikegioia** [comment]
@kevin93w Would you be able to provide the events array too? Even is a jsfiddle or paste dump would be good, I just want to run the same thing you are.

**Comment by kevin93w** [comment]
@mikegioia Sure mike, I receive the events from an AJAX request and pass the events into the function. Here is a json example of how the events array could look like:

[
    {
        "date": "2015-07-01",
        "id": "57",
        "type": "consultation"
    }, {
        "date": "2015-07-02",
        "id": "58",
        "type": "consultation"
    }, {
        "date": "2015-07-03",
        "id": "105",
        "type": "full"
    }, {
        "date": "2015-09-30",
        "id": "134",
        "type": "consultation"
    }
]

**Comment by kylestetz** [comment]
@kevin93w what versions of jQuery, underscore, and moment are you using? Moment has had some problems in the past with IE support, and you will need to be on the `1.x` branch of jQuery (jQuery `2.x` does not support IE <= 8).

Please also include the version of clndr.js you're using, since `1.2.12` was just put out last week.

**Comment by kevin93w** [comment]
@kylestetz The errors are occurring on many versions of IE, including the newer ones up to IE10 and IE11 (Tested through multiple platforms and BrowserStack).

The versions I use:

jQuery - 1.10.1
Modernizr - 2.6.2
HTML5Shiv - 3.7.3
MomentJs - 2.9.0
UnderscoreJs - 1.8.3
ClndrJs - 1.2.10

**Comment by kevin93w** [comment]
I have updated the ClndrJs version to 1.2.12, the problem persists. I noticed that while the array does contain events for all of the months displayed, it seems to put all returned events onto the first of July in the first calendar. While the two other calendars remain empty... So I guess the problem has something to do with IE and my Underscore template in combination with the events array.

**Comment by mikegioia** [comment]
I think this might be the moment library not correctly parsing the date. The only time that error (everything landing on the same day) happened to me it was when the date processing failed. I think it's hitting July 1 because it's today, and the fallback for the failed parsing is to load it for today.

Are you able to test moment.js at all, or try out their demos on their website?

**Comment by kevin93w** [comment]
Unfortunately I don't have my development suite installed on a Windows platform, so I'm not able to debug the code on IE. I did try and debug the code itself, also the dependencies, but did not find any unexpected flows.

Is the date format in my array and StartsWithMonth attribute syntactically correct to work with ClndrJs and Moment?

**Comment by kylestetz** [comment]
@kevin93w yes, your dates are correctly ISO formatted (YYYY-MM-DD). That is definitely not the issue.

I just ran the `test.html` page in my IE8 environment (virtual box) and it failed on `clndr.multiDayMixedPerformance`. @kevin93w I think clndr is the cause!

Unfortunately I am not in a position to check this out thoroughly at the moment. I will do so as soon as I can.

**Comment by mikegioia** [comment]
I just cloned 1.2.12 in Windows 7 and tested example/index.html in Win11 and it worked. I created another file in `example/` locally on windows and dumped the following (excuse the formatting/lack of css) code and it also ran as expected. You should see the day number and the count of events for that day.

http://pastie.org/10268380

I'm not sure if I can reproduce this.

**Comment by kevin93w** [comment]
@kylestetz @mikegioia Okay, so perhaps it has something to do with the failing tests. I already thank you for the quick responses, so please take the time necessary to check the issue out! I also tried the pastie you sent, but I don't seem to get it to work in my environment. It only shows the header blocks with the name of the month in it (so no events or anything else). Also worth mentioning that I only use parts of the clndr.css code in my own css file and edited it to my own needs. You can check it here http://pastie.org/10268397

**Comment by kevin93w** [comment]
Hi guys, any news yet or no time so far checking the issue out or reproducing it?

**Comment by mikegioia** [comment]
Sorry, @kevin93w I still have to clone and run the tests in an IE/Windows set up. I only have VMs to work with but I should be able to tomorrow.

I patched a bug today in 1.2.14 so if you could try with that I'd appreciate it, but otherwise I'll let you know what the tests return for me.

**Comment by kevin93w** [comment]
Hi @mikegioia, I updated to the new version 1.2.14 like you suggested. It did have some effect, in the sense that the rendering failure is not on the first day of the month but in this case on the 9th day (I do not now why, because it is not the first day an event takes place that month). I added a screenshot below for you to check it out.

![schermafbeelding 2015-07-09 om 12 52 24](https://cloud.githubusercontent.com/assets/7465924/8593618/a3c18c9a-2639-11e5-8241-19ca56732dc0.png)

**Comment by mikegioia** [comment]
@kevin93w I just now opened this back up in IE on Win11 and still couldn't replicate any errors. Nothing in the tests broke except for in IE8 (which I can no longer support anyway). I just can't see any issues here in IE. I pulled the now latest 1.4.3 and ran the tests and I'd invite you to do the same.

At this point, I'll need something in JSBin or JSFiddle that I can open in a browser and edit in my Windows VM to test. If it's possible, can you copy this config/html/js to one of those services and send the link to recreate the errors your seeing? If you can send something in one of those services that I can open in Windows/IE and recreate then I'll absolutely be able to resolve it. I'm going to mark this as stale for now since it's so old, but if you're able to get to this in the next week or so I can keep at it.

**Comment by mikegioia** [comment]
I'm going to close this out but feel free to re-open it if it's still an issue for you.
