### ISSUE TITLE
How can I disable specific days

### ISSUE THREAD

**Issue by piegus** [kylestetz/CLNDR#195]
Hey. 
Im working right now on implementing clndr on one of the sites. I need to disable specific days from Ajax request. How can I achieve this??

**Comment by mikegioia** [comment]
@piegus What do you mean by "disable specific days"? You have full control over the template during render so you always have the option to add logic to your template or via CSS to hide specific days. You could add certain classes to the day and hide them that way.

Or do you mean have CLNDR hide days?

**Comment by abraovic** [comment]
Hi **@mikegioia**,

I have the same question. What I was wondering if there is an option in which you can define an array of dates that you want to exclude?

e.g.
```javascript
var array = ["8-14-2015"," 8-21-2015"];

$('.parent-element').clndr({
    // ... some previous setup
    excludeDates: array,
    // continue on setup ...
});
```

As I can see in the available options, you do not have this. I was wondering if you are planning to have something like this?

Thanks,
Ante.

**Comment by mikegioia** [comment]
I think it's a good suggestion, but I'm not sure this is something that should be included in the library. @kylestetz might want to weigh in, but this seems like it should be handled outside. In my own app that uses CLNDR, I set up template logic to exclude weekends.

I haven't yet investigated what side-effects excluding days could cause. For one, I think this setting would break all of the tests/example files since the days would no longer sync with the headings. However, I'm assuming you're using this outside of the monthly/weekly view.

Are you currently able to post-process the days array in your app code to remove these dates?

**Comment by kylestetz** [comment]
I agree with @mikegioia, this is a templating concern. @abraovic, did you know about the `extras` option in clndr? Whatever you put in there will be available in your template. I am imagining a function that excludes those blacklisted days, which you could use to prepare the correct `each` loop:

```javascript
<% _.each( excludeDates(days), function(day) { %>
  <div class='<%= day.classes %>'><%= day.day %></div>
<% }); %>
```

**Comment by webteckie** [comment]
Perhaps add the ability for CLNDR to have plugins?  That way different functionality can be optionally available without it being part of the core library.

**Comment by mikegioia** [comment]
@webteckie That's an interesting idea, but I'm not sure where in the init/render a plugin would be useful. In order to implement excludeDays via a plugin you would have to hook into either/both of the render and createDaysObject.

There's actually two hook-points @piegus could use to possibly achieve date exclusion: `options.doneRendering` is triggered right after the render, and `options.ready` is triggered right after the initialization. In either you could modify the internal days array to do whatever you wanted.

Lemme know what you think, I do however feel this ticket is a candidate for wont-fix.

**Comment by webteckie** [comment]
@mikegioia feel free to close it if the original issue was solved or has a workaround.  Mines was just a vague suggestion.
