### ISSUE TITLE
Calling render() after startDate does not work as expected

### ISSUE THREAD

**Issue by james-daddies** [kylestetz/CLNDR#241]
I have two calendars used for a date range type setup. Select on date and then depending on a duration, I set the startDate for the second calendar accordingly. 

When the startDate goes into the next month, calling `render()` only updates the days but does not move the calendar to the correct month.

Would there be another method I need to call or could this be an enhancement?

**Comment by mikegioia** [comment]
@james-daddies I think what you're looking for may be here: https://github.com/kylestetz/CLNDR#returning-the-instance--public-api

Otherwise, I must apologize but we're trying to keep the GH issues to be bugs/PRs only. If you wouldn't mind, could you take this to Stack Overflow until it's confirmed to be a bug?
