### ISSUE TITLE
Adjacent month class not showing with different interval lengthOfTime

### ISSUE THREAD

**Issue by Mattia-Nocerino** [kylestetz/CLNDR#244]
I tried to make a weekly calendar by setting this length of time:

`lengthOfTime: {
  months: null,
  days: 7,
  interval: 7
}`

And it's working fine, but it doesn't add the adjacentmonth class to the days of the adjacent months!

**Comment by mikegioia** [comment]
Hi @Mattia-Nocerino, if at all possible could you submit a PR with a reproducible test case for me to ID the bug in question? I think the problem here is that you specified a "weeks" interval and are expecting months logic to exist. I'm not sure if adjacentMonths makes any sense in a weekly calendar context.

Some weeks could have two months within them, but if you're able to come up with a way that makes sense, please submit the PR and I'd be happy to review it.
