### ISSUE TITLE
Wrong dates even in the live demos

### ISSUE THREAD

**Issue by qwertyuu** [kylestetz/CLNDR#284]
#### Context

I went to http://kylestetz.github.io/CLNDR/ and the dates shown on the calendars are wrong
#### Expected Behavior

CLNDR should at least show the right dates, or fit the native Windows calendar
#### Actual Behavior

![wrong dates](https://cloud.githubusercontent.com/assets/3145639/18976191/00445d08-867e-11e6-80b7-5f0c251603df.JPG)
The bottom line of the calendar showing dates for the next month is then offset by 1 day, rendering the bottom line + the first day of October totally useless
#### Steps to Reproduce

1. Go to http://kylestetz.github.io/CLNDR/
2. Check the date
#### Your Environment

- Version used: Latest available on http://kylestetz.github.io/CLNDR/
- Browser Name and version: FF 49.0.1 & Chrome
- Operating System and version (desktop or mobile): Windows 10 non-anniversary

**Comment by mikegioia** [comment]
Thanks @qwertyuu. I'll try to check this out today or tomorrow.

**Comment by mikegioia** [comment]
Sorry for the delay, I'm going to try to look at this today.

**Comment by mikegioia** [comment]
Ugh this is even more annoying because I can't reproduce it in the test file >_<

I'll have to mimic the configuration from Kyle's website.

**Comment by mikegioia** [comment]
@qwertyuu I think this was because gh-pages used version 1.2.6 (way old). I just updated it to the latest version of CLNDR and it looks like it's working: http://kylestetz.github.io/CLNDR/

What I would ask, if you're able to recreate the error in the test file first that would be helpful. I'll have to be more mindful about updating CLNDR in the github pages branch in the future though.

**Comment by long-lazuli** [comment]
related to #282

**Comment by mikegioia** [comment]
I can't recreate this and I think it's gone stale. I'm almost positive this was related to an old version of the library.
