### ISSUE TITLE
Previous and Next months appear. I just want to show the current month.

### ISSUE THREAD

**Issue by oguzhansari** [kylestetz/CLNDR#333]
#### Context
Hi,
I do not want to show the previous and next months.
I use my own design.
I just want you to see the moon we find.
I am setting "showAdjacentMonths" to "false".
The data of the previous and next months do not come, but the element looks.

See Picture;
![clndr js-error](https://user-images.githubusercontent.com/13555457/43365418-7054ecf0-9335-11e8-8640-b7e89063ec8c.JPG)

What do I wnat to do (quoted from the PSD file);
![yapmak-istedigim](https://user-images.githubusercontent.com/13555457/43365573-9283ac38-9337-11e8-9e42-b29d027999a9.JPG)

#### Expected Behavior
The element should never be created.

#### Actual Behavior

...

#### Possible Fix

...

#### Steps to Reproduce

1. https://jsfiddle.net/ax7f5046/

#### Your Environment

* Version used: 1.4.7
* Browser Name and version: Chrome 67.0.3396.99 (Offical Compilation) (64 Bit)
* Operating System and version (desktop or mobile): Desktop Windows 10 (Most Recent Version)
* Link to your project: -

**Comment by mikegioia** [comment]
@oguzhansari I can't confirm exactly what's going on but that doesn't look like the adjacent months at first glance. I would say though that this question would get more help at Stack Overflow. If you're able to trace the bug and can reproduce it in JS Fiddle, please resubmit it here.

**Comment by oguzhansari** [comment]
Published the example in JSFiddle.
Link: https://jsfiddle.net/ax7f5046/

You have to give it a solution.
You are the manufacturer.
You should know the source better.

I do not want the days of the previous and next months to be displayed.
"showAdjacentMonths": false Do not you have to set this setting for me?

**Comment by mikegioia** [comment]
@oguzhansari Please read the readme and follow the format for issuing bug reports. I don't have the time to read and digest this kind of a custom problem. Run through our tests, see if you can hit the error in there. If you can, re-issue a proper ticket using the issue template we have.

**Comment by kylestetz** [comment]
Hey @oguzhansari, sorry for the confusion about `showAdjacentMonths`— clndr will always render a complete grid of days (e.g. complete rows of seven boxes), and `showAdjacentMonths` simply controls whether the date is visible within those boxes, or whether they are empty. This is not a bug and is by design; most calendars out there are rendered as a grid.

You can fix this issue by either adding a check in your template to see if the `day.day` field has a value (it will be an empty string in the case of those boxes you want to get rid of) or you can add the line of css `.day.empty { display: none; }`, which uses the `.empty` class on those dates to hide them.

I'm keeping this closed this since it isn't an issue with the library, but you're welcome to submit a PR if you have an idea for how clndr can be extended to make this situation easier.

**Comment by oguzhansari** [comment]
@kylestetz Thanks.

"Display: none" is only hidden.
I've had problems with CSS ( example >   :nth-child(n+15)).
It's influenced by hidden elements.
I deleted the elements with the class name "empty". (JS: $('.day.empty').remove())
You can see my work here.
Video: http://sendvid.com/vhmtzoek
