### ISSUE TITLE
Generating `daysOfTheWeek` array with only first character

### ISSUE THREAD

**Issue by aprat84** [kylestetz/CLNDR#342]
https://github.com/kylestetz/CLNDR/blob/555cf44c19dbf719c559a3ae86314d3eae0c5a25/src/clndr.js#L348

When this plugin generates `daysOfTheWeek` array from momentjs localized `dd` format, it only considers the first character, even when it formats it with the "min" version from momentjs.

In Catalan, for example, every day name begins with same letter `d` (dilluns, dimarts, dimecres, ...), so I end up having a day names header full of `D`.

Would you consider respecting whatever comes from momentjs when formatting it with `dd`?
Or at least, give an option to let us chose without the need to fill this array everytime we instantiate a new CLNDR?

Thanks!

**Comment by mikegioia** [comment]
@aprat84 That's a really good catch and I had never noticed or considered that before. I think we probably have to honor the `dd` format, however I think converting from one character to two is a breaking change :( We might be able to avoid the breaking change by adding a conditional check to see if the locale is != 'english'. Perhaps for now we use `dd` for anything non-English and then later on we can make the full breaking change for English too.

Something like this:

```
if (moment.locale() === 'en') {
  moment().weekday(i).format('dd').charAt(0);
} else {
  moment().weekday(i).format('dd');
}
```

That could help allow us to increment the version to 1.6 instead of 2.0, but it would break for anyone not using the 'en' locale. I still think that's okay because what you've shown probably means many non-english clndr users are probably correcting this themselves.

The only other option would be to add a new setting, something like `weekday_length` and the default would be `1`. You could then configure it with `2` (or something) and that could also avoid the breaking change.

What do you think?

**Comment by kylestetz** [comment]
@aprat84 thanks for pointing this out, we definitely want to support more flexible day headers. 

@mikegioia I like your idea! What if we take it a tad further and expose a function `formatWeekdayHeader` that exposes a moment object set to the correct weekday and allows you to return any string? That would allow you to run both `.format('dd')` or do some more complicated logic for a given locale (like we currently do with `charAt`). The default could be `(m) => m.format('dd').charAt(0)` or we could improve things by doing the `en` locale check that you suggested. I like this because it also opens up the possibility of e.g. doing completely custom headers by inspecting `m.weekday()` and pulling from your own array of strings.

```javascript
$('.calendar').clndr({
  ...
  formatWeekdayHeader: (day) => day.format('dd'),
})
```

Thoughts? Would this work for you @aprat84?

**Comment by mikegioia** [comment]
Yea I think keeping the current as the default and adding the `formatWeekdayHeader` function is the best solution.

**Comment by aprat84** [comment]
Thanks for fast reply!

I like @kylestetz's function idea best. It give us users 100% flexibility to choose whatever format fits better.

IMHO, in the future, I would use `dd` format as is, no matter the locale. That's what almost any other datepicker does (jquery-ui, bootstrap, vaadin, webix, kendo UI, ...)

**Comment by kylestetz** [comment]
Yep totally hear you about using `dd` by default — this is a mistake of history (I had never worked in an internationalized codebase when I wrote this plugin!) but we also want to avoid thrash for existing users. Bumping to 1.6 and defaulting to `dd` seems reasonable. @mikegioia how does that sound?

**Comment by mikegioia** [comment]
Sorry, @kylestetz I'm a little confused. Are we including the new option `formatWeekdayHeader` or just changing the code to remove the `.charAt(0)`? I usually tend to avoid at all costs anything that changes what is rendered but in this case I'll cede if you think it's just better to do and would fix more than it breaks.

**Comment by kylestetz** [comment]
Sorry for the confusion: I'm still advocating for adding the `formatWeekdayHeader` option, but also changing the default value for _everyone_ to `dd` too if we bump to 1.6.0. If you have strong feelings about keeping the defaults as-is, though, totally fine by me.

**Comment by mikegioia** [comment]
Thanks Kyle. Sorry for being so stubborn here, I just did a check in our app for work and noticed it would currently change the display unless I updated the config, and it made me think we could be doing that for other people. That coupled with the fact that OP and any current user can just use the `daysOfTheWeek` option to resolve this leads me to want to avoid a breaking change for something like. This is my full proposal, but I will definitely defer to you if you want to make a change/executive decision:

1. Add `formatWeekdayHeader` as a new option as you have it defined
2. Keep the `.charAt(0)` for the time being
3. Bump the version to 1.5.1
4. Add a GH issue / comment in the code to fix this for the 2.0 release

The 2.0 release would be additionally interesting and could be a vehicle to ES6-ify this repo and/or chop it up into modules as you originally visioned.

**Comment by kylestetz** [comment]
You're not being stubborn at all, thanks for clarifying! Your proposal sounds good.

**Comment by mikegioia** [comment]
@kylestetz I sent the small PR up here: https://github.com/kylestetz/CLNDR/pull/343

**Comment by mikegioia** [comment]
@aprat84 @kylestetz This is now added to version 1.5.1, and updated in NPM!
