### ISSUE TITLE
 Drop jQuery dependency

### ISSUE THREAD

**Issue by GeoSot** [kylestetz/CLNDR#349]
Hello @kylestetz 
This plugin have save my ass many times. THANK YOU :)

But as i have used it some times, I was wandering if it could be more independent.
 
Have you ever thought to drop jQuery dependency?
I had a quick view of the code, and I think it would be a great boost on your plugin and without a great effort.

As a second thought it would be also great if we could avoid the usage of moment.js giant that brings a tone of KBs  . I don't know if you are aware of these [alternatives](https://github.com/you-dont-need/You-Dont-Need-Momentjs)

**Comment by kylestetz** [comment]
Hey @GeoSot — yes, the frontend landscape has changed quite a bit since this plugin was first created. We are keeping this project in maintenance mode as we don't have the time or interest in taking on a modern rewrite, but you are welcome to fork the repo, take a stab at it, and present the results in an issue here if you'd like.

Cheers 🍻
